services:
  - type: web
    name: cuartoya-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cuartoya-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: CULQI_PUBLIC_KEY
        sync: false
      - key: CULQI_SECRET_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: RENIEC_API_TOKEN
        sync: false
    healthCheckPath: /health

databases:
  - name: cuartoya-db
    plan: free
    databaseName: cuartoya_db
    user: cuartoya_user
